--Felecia Gonzalez

--1
SELECT BOOK_SUBJECT, COUNT(BOOK_NUM) AS "Books In Subject"
FROM BOOK
GROUP BY BOOK_SUBJECT
ORDER BY COUNT(BOOK_NUM) DESC
LIMIT 3;

--2
SELECT CONCAT(CONCAT(PAT_FNAME, ' '), PAT_LNAME) AS "Full Name"
FROM PATRON
WHERE PAT_ID IN (SELECT CHECKOUT.PAT_ID FROM CHECKOUT WHERE CHECK_IN_DATE > CHECK_DUE_DATE)
ORDER BY PAT_LNAME;

--3
SELECT UPPER(AU_LNAME) AS "Author's Last Name", BOOK_TITLE AS "Book Title", CONCAT('$', CAST(BOOK_COST AS CHAR(5)) AS "Book Cost"
FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID JOIN BOOK ON WRITES.BOOK_NUM = BOOK.BOOK_NUM
WHERE BOOK_COST > 60 AND BOOK_COST < 80
ORDER BY AU_LNAME;
