SELECT EMP_NUM,EMP_LNAME, EMP_FNAME, EMP_INITIAL
FROM EMPLOYEE
WHERE EMP_LNAME LIKE 'Smith%'
ORDER BY EMP_NUM;

SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT, JOB, EMPLOYEE
WHERE PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM AND JOB.JOB_CODE = EMPLOYEE.JOB_CODE;

SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT, JOB, EMPLOYEE
WHERE PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM AND JOB.JOB_CODE = EMPLOYEE.JOB_CODE
ORDER BY EMP_LNAME;

SELECT DISTINCT PROJ_NUM
FROM ASSIGNMENT
ORDER BY PROJ_NUM;

SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, ASSIGN_HOURS*ASSIGN_CHG_HR AS CALCULATED_CHARGE
FROM ASSIGNMENT
ORDER BY ASSIGN_NUM;

SELECT ASSIGNMENT.EMP_NUM, EMP_LNAME, SUM(ASSIGN_HOURS), SUM(ASSIGN_CHARGE)
FROM ASSIGNMENT, EMPLOYEE
WHERE ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
GROUP BY ASSIGNMENT.EMP_NUM
ORDER BY ASSIGNMENT.EMP_NUM;

SELECT PROJ_NUM, SUM(ASSIGN_HOURS), SUM(ASSIGN_CHARGE)
FROM ASSIGNMENT
GROUP BY PROJ_NUM
ORDER BY PROJ_NUM;

SELECT SUM(ASSIGN_HOURS), SUM(ASSIGN_CHARGE)
FROM ASSIGNMENT;
