SELECT CHECK_NUM, BOOK_NUM, CHECK_OUT_DATE
FROM CHECKOUT
WHERE CHECK_OUT_DATE < '2017-04-05'
ORDER BY CHECK_NUM;

SELECT BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, BOOK_COST
FROM BOOK
WHERE BOOK_SUBJECT IN ('Cloud', 'Middleware') AND BOOK_COST > 70
ORDER BY BOOK_NUM;

SELECT AU_ID, AU_FNAME, AU_LNAME, AU_BIRTHYEAR
FROM AUTHOR
WHERE AU_BIRTHYEAR BETWEEN 1980 AND 1989
ORDER BY AU_ID;

SELECT COUNT(BOOK_NUM) AS "Available Books"
FROM BOOK
WHERE PAT_ID IS NULL;

SELECT AU_ID, COUNT(BOOK_NUM) AS "Books Written"
FROM WRITES
GROUP BY AU_ID
ORDER BY COUNT(BOOK_NUM) DESC, AU_ID ASC;

SELECT AUTHOR.AU_ID, AU_FNAME, AU_LNAME, BOOK.BOOK_NUM, BOOK_TITLE
FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
WHERE BOOK_SUBJECT = "Cloud"
ORDER BY BOOK_TITLE, AU_LNAME;

SELECT BOOK.BOOK_NUM, BOOK_TITLE, COUNT(CHECK_NUM) AS "Times Checked Out"
FROM BOOK LEFT JOIN CHECKOUT ON BOOK.BOOK_NUM = CHECKOUT.BOOK_NUM
GROUP BY BOOK.BOOK_NUM
ORDER BY COUNT(CHECK_NUM) DESC, BOOK_TITLE ASC;

SELECT AUTHOR.AU_ID, AU_LNAME, BOOK_TITLE, CHECK_OUT_DATE, PAT_LNAME
FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM JOIN CHECKOUT ON CHECKOUT.BOOK_NUM = BOOK.BOOK_NUM JOIN PATRON ON PATRON.PAT_ID = CHECKOUT.PAT_ID
WHERE AU_LNAME = 'Bruer' AND PAT_LNAME = 'Miles'
ORDER BY CHECK_OUT_DATE;

SELECT PATRON.PAT_ID, PAT_FNAME, PAT_LNAME
FROM PATRON
WHERE PATRON.PAT_ID NOT IN (SELECT CHECKOUT.PAT_ID FROM CHECKOUT)
ORDER BY PAT_LNAME, PAT_FNAME;

SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST
FROM BOOK
WHERE BOOK_COST = (SELECT MIN(BOOK_COST) FROM BOOK)
ORDER BY BOOK_NUM;

SELECT AUTHOR.AU_ID, AU_FNAME, AU_LNAME
FROM AUTHOR
WHERE AUTHOR.AU_ID NOT IN(SELECT AUTHOR.AU_ID FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM WHERE BOOK_SUBJECT = 'Programming')
ORDER BY AU_LNAME;

SELECT BOOK.BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, AU_LNAME, (SELECT COUNT(WRITES.BOOK_NUM) FROM WRITES WHERE AUTHOR.AU_ID = WRITES.AU_ID GROUP BY AU_ID) AS "Num Books Written by Author"
FROM AUTHOR JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
WHERE BOOK_SUBJECT = 'Cloud'
ORDER BY BOOK_TITLE, AU_LNAME;
